---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: port-scan-exporter
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: port-scan-exporter
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: port-scan-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: port-scan-exporter
subjects:
- kind: ServiceAccount
  name: port-scan-exporter
  namespace: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: port-scan-exporter
  namespace: monitoring
  labels:
    app: port-scan-exporter
spec:
  template:
    metadata:
      labels:
        app: port-scan-exporter
    spec:
      serviceAccountName: port-scan-exporter
      containers:
      - name: port-scan-exporter
        image: ghcr.io/gacko/port-scan-exporter:latest
        ports:
        - name: metrics
          containerPort: 8000
        livenessProbe:
          httpGet:
            port: metrics
            path: /healthz
        readinessProbe:
          httpGet:
            port: metrics
            path: /healthz
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 200Mi
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: port-scan-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: port-scan-exporter
  namespace: monitoring
  labels:
    app: port-scan-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 8000
    targetPort: metrics
  selector:
    app: port-scan-exporter
