apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "port-scan-exporter.fullname" . }}
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "port-scan-exporter.fullname" . }}
    verbs:
      - use
