apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "port-scan-exporter.fullname" . }}
  namespace: {{ include "port-scan-exporter.namespace" . }}
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "port-scan-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "port-scan-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT_SCAN_EXPORTER_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - --listen
            - ":{{ .Values.service.port }}"
          ports:
            - name: metrics
              protocol: TCP
              containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              port: metrics
              path: /healthz
          readinessProbe:
            httpGet:
              port: metrics
              path: /healthz
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "port-scan-exporter.selectorLabels" . | nindent 6 }}
