---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "port-scan-exporter.fullname" . }}
  namespace: {{ include "port-scan-exporter.namespace" . }}
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "port-scan-exporter.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "port-scan-exporter.selectorLabels" . | nindent 14 }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
        - podSelector:
            matchLabels:
              app: prometheus
        {{ $privateSubnets := list "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
        {{ range $index, $privateSubnet := $privateSubnets }}
        - ipBlock:
            cidr: {{ $privateSubnet }}
        {{ end }}
        ports:
          - protocol: TCP
            port: 8000
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "port-scan-exporter.selectorLabels" . | nindent 14 }}
        {{ $privateSubnets := list "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
        {{ range $index, $privateSubnet := $privateSubnets }}
        - ipBlock:
            cidr: {{ $privateSubnet }}
        {{ end }}
