apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "port-scan-exporter.fullname" . }}
  namespace: {{ include "port-scan-exporter.namespace" . }}
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "port-scan-exporter.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "port-scan-exporter.selectorLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    - podSelector:
        matchLabels:
          app: prometheus
    {{- range .Values.privateSubnets }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
    ports:
    - protocol: TCP
      port: 8000
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "port-scan-exporter.selectorLabels" . | nindent 10 }}
    {{- range .Values.privateSubnets }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
{{- range .Values.isolatedNamespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "port-scan-exporter.fullname" $ }}
  namespace: {{ . }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ include "port-scan-exporter.namespace" $ }}
      podSelector:
        matchLabels:
          {{- include "port-scan-exporter.selectorLabels" $ | nindent 10 }}
{{- end }}
