apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "port-scan-exporter.fullname" . }}
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
spec:
  privileged: false
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: true
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  allowPrivilegeEscalation: false
  seLinux:
    rule: RunAsAny
