{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "port-scan-exporter.serviceAccountName" . }}
  namespace: {{ include "port-scan-exporter.namespace" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
{{- end }}
