apiVersion: v1
kind: Service
metadata:
  name: {{ include "port-scan-exporter.fullname" . }}
  namespace: {{ include "port-scan-exporter.namespace" . }}
  labels:
    {{- include "port-scan-exporter.labels" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: metrics
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8000
  selector:
    {{- include "port-scan-exporter.selectorLabels" . | nindent 4 }}
