---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: port-scan-exporter
  labels:
    app: port-scan-exporter
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - port-scan-exporter
  verbs:
  - use
