---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: port-scan-exporter
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: port-scan-exporter
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: port-scan-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: port-scan-exporter
subjects:
- kind: ServiceAccount
  name: port-scan-exporter
  namespace: monitoring
