# Default values for port-scan-exporter.

# Chart.
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

# Network policy.
privateSubnets:
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16
- 100.64.0.0/10

# Service account.
serviceAccount:
  create: true
  name: ""
  annotations: {}

# Daemon set: Pod.
podAnnotations: {}
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
imagePullSecrets: []
tolerations:
- operator: Exists

# Daemon set: Container.
securityContext: {}
  #runAsUser: 1000
  #runAsGroup: 1000
image:
  repository: ghcr.io/gacko/port-scan-exporter
  tag: ""
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    cpu: 1
    memory: 512Mi

# Service.
service:
  type: ClusterIP
  port: 8000
