# Default values for port-scan-exporter.

# Chart.
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

# Network policy.
privateSubnets:
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16
- 100.64.0.0/10

# Service account.
serviceAccount:
  create: true
  name: ""
  annotations: {}

# Pod.
podAnnotations: {}
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
imagePullSecrets: []
tolerations:
- operator: Exists

# Container.
securityContext: {}
  #runAsUser: 1000
  #runAsGroup: 1000
image:
  repository: ghcr.io/gacko/port-scan-exporter
  pullPolicy: IfNotPresent
  tag: ""
resources: {}
  #limits:
  #  cpu: 1000m
  #  memory: 512Mi
  #requests:
  #  cpu: 500m
  #  memory: 256Mi

# Service.
service:
  type: ClusterIP
  port: 8000
